[General]
key_pmi=7010465046
key_pmi_invite_msg="Michael Nielson is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Michael Nielson's Personal Meeting Room\r\nJoin Zoom Meeting\r\nhttps://us04web.zoom.us/j/7010465046?pwd=2phUNGaeJaiFA8TSCfYalu5tLcLVYv.1\r\n\r\nMeeting ID: 701 046 5046\r\nPasscode: GG2Bfu\r\n\r\n\r\n"
